packages:
  - .

allowBuilds:
  unrs-resolver: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes

overrides:
  chokidar: '>=5'
  semver: '>=7'
  vite@>=7.0.0 <=7.3.1: '>=7.3.2'
  vite@>=8.0.0 <=8.0.4: '>=8.0.5'

trustPolicy: no-downgrade
