name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: codebuild-codebuild-gha-lambda-runner-example-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
    - uses: actions/checkout@v5

    - uses: oven-sh/setup-bun@v2

    - name: Build app
      run: |
        bun install
        bun run build

    - name: test
      run: aws --version
